---
- name: I am hacking your website
  hosts: all
  tasks:
  - name: Create websites directory under /home/vagrant/
    file:
      path: /home/vagrant/websites
      state: directory
      owner: vagrant
      group: vagrant
      mode: '0755'
  - name: Download website templates
    get_url:
      url: https://github.com/m1820/atd/blob/master/sites/sites.tgz?raw=true
      dest: /home/vagrant/websites
  - name: Extract sites.tgz into /home/vagrant/websites
    unarchive:
      src: /home/vagrant/websites/sites.tgz
      dest: /home/vagrant/websites
      remote_src: yes
  - name: Copy hacked site to /var/www/html
    copy:
      src: /home/vagrant/websites/sites/hacked/
      dest: /var/www/html
      remote_src: true 